#!/usr/bin/env bash
source ../../../../bash_json_functions

extract_json "| map(select(.analysisParameters.minTopAlleleFreqQ2 == "0.50"))" "chrIV:14,941,896" ".disagreements" ${1}stats.json ${1}filtered.json
compare_jsons ${1}filtered.json disagreement.json_preserve
touch run.out.check custom_check
