language: java
jdk: oraclejdk8
before_install:
  - sudo apt-get update
  - sudo apt-get install perl
  - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
  - sudo cpanm File::Grep
install:
script: "cat /home/travis/build/cinquin/mutinack/cov-int/build-log.txt ; rm -Rf build bin lib_unjarred && ant clean insert-git-info unjar_dependencies && ant jar junitreport && ./run_functional_tests"

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WMfwT1odo6tax0JW/wS9V862M7Oree0sp7XisLGgigEbFrDbEjeYkV68mUDJ/yHt0gh4TsSgBzH4LOFWL6fw97zKzhhC6Boqgn+mH201uZnCLBBS5MXNPwFx0QCd0aP8Re6zDWcQtGoX2mFAgkrDKGuG8mF9ZUvB3VgTjDiCRdc="

addons:
  coverity_scan:
    project:
      name: "cinquin/mutinack"
      description: "<Your project description here>"
    notification_email: olivier.cinquin@uci.edu
    build_command_prepend: "true"
    build_command:   "ant"
    branch_pattern: "coverity"

