language: c
language: java
jdk: oraclejdk8

branches:
  only:
  - master

addons:
    apt:
        packages:
            - oracle-java8-installer
            - libonig-dev
            - valgrind
            - bison

before_install:
  - sudo apt-get update
  - sudo apt-get install perl
  - sudo apt-get install gettext
  - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
  - sudo cpanm File::Grep
  - ./before_install_jq

install:
  - ./install_jq

before_script:
  - ./before_script_jq

script: "cat /home/travis/build/cinquin/mutinack/cov-int/build-log.txt ; rm -Rf build bin lib_unjarred && ant clean insert-git-info unjar_dependencies && ant jar junitreport && ./build_jq && (cd nailgun && make && mvn install) && ./run_functional_tests"

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Otg4WpE9kRMo7Bbej550R58P/dj9T9tZB9O9vn6cvV0nkaNxcmZ2lMdEdeDfTVatoqPtHeMqu2bafvLpw+q1OKAeSsfmPiKzLRSZjl43rO7qZ6Sqr/Zkky6NoAKp4x10CgfDOFjzdCBl6GMPdARH7n7JcYXneWLi64V/CgcW76E="

addons:
  coverity_scan:
    project:
      name: "cinquin/mutinack"
      description: "<Your project description here>"
    notification_email: olivier.cinquin@uci.edu
    build_command_prepend: "ant clean"
    build_command: "ant"
    branch_pattern: "coverity"
