language: c
language: java
jdk: oraclejdk8
before_install:
  - sudo apt-get update
  - sudo apt-get install perl
  - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
  - sudo cpanm File::Grep
install:
script: "cat /home/travis/build/cinquin/mutinack/cov-int/build-log.txt ; rm -Rf build bin lib_unjarred && ant clean insert-git-info unjar_dependencies && ant jar junitreport && (cd nailgun && make && mvn install) && ./run_functional_tests"

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VM70K4BxRrdGwtcOGH4V5rx4lLR1qmDt8Ql4OHFVvo+3bj/6j0C6SYV8mfCgpVeH15AyHrCP0HgD5lm+mirqV3miDjzeTb476PWa1TBl2r/RJhXg8F3z+Cuhb7Z0O0lwVS754xkfKds0oowEhUt9+XNTgZ0QJ4aDl5t1KnFRC0s="

addons:
  coverity_scan:
    project:
      name: "cinquin/mutinack"
      description: "<Your project description here>"
    notification_email: olivier.cinquin@uci.edu
    build_command_prepend: "ant clean"
    build_command: "ant"
    branch_pattern: "coverity"

