#!/bin/bash
(nohup java -Djava.security.policy==java.policy -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:CICompilerCount=3 -javaagent:lib/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=target/jacoco.exec -jar mutinack.jar -startWorker localhost &> run_worker_out) &
echo $!
