#!/bin/bash
(nohup java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6606 -cp mutinack.jar:nailgun/nailgun-server/target/nailgun-server-0.9.2-SNAPSHOT.jar com.martiansoftware.nailgun.NGServer &> run_nailgun_server_out) &
echo $!
