#!/bin/bash
set -o pipefail
set -e
tmp_dir=$(mktemp -d /tmp/Nailgun_server_PID.XXXXXX)
trap 'rm -Rf "$tmp_dir"' EXIT INT TERM HUP
tmp_pipe=${tmp_dir}/pid
mkfifo -m 600 "${tmp_pipe}"
(java -Djavax.net.ssl.trustStore=mutinack_public_trustStore -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.keyStore=mutinack_public_selfsigned.jks -Djavax.net.ssl.keyStorePassword=passphrase -cp mutinack.jar:nailgun/nailgun-server/target/nailgun-server-0.9.2-SNAPSHOT-jar-with-dependencies.jar com.martiansoftware.nailgun.NGServer --writePID ${tmp_pipe} 127.0.0.1 > run_nailgun_server_out ; echo FAILED > ${tmp_pipe} ) > /dev/null  &
result=`cat "${tmp_pipe}"`
if [ "${result}" = "FAILED" ];
then
    exit 1
fi
echo ${result}
