#!/usr/bin/env bash
set -e
set -o pipefail
source ../../../bash_json_functions

extract_json "| map(select(.analysisParameters.minBasePhredScoreQ2 == 24)) | map(select(.analysisParameters.minReadsPerStrandQ2 == 3)) | map(select(.analysisParameters.randomizeStrand == true))" "chrX:11,857,476" "" ${1}stats.json ${1}filtered.json
#Uncomment line below to check that error is generated if JSON objects differ
#echo '[{"blah": 0}]' >> filtered.json
extract_json "map(select(.analysisParameters.minBasePhredScoreQ2 == 25))" "chrX:11,857,476" ""  ../../test_options/positive_strand/minBasePhredScoreQ2/test_Q2_score_27_criteria_25_substitution_detection/stats.json ${1}filtered_no_range_exploration.json
compare_jsons ${1}filtered.json ${1}filtered_no_range_exploration.json

extract_json "map(select(.analysisParameters.minBasePhredScoreQ2 == 24)) | map(select(.analysisParameters.minReadsPerStrandQ2 == 3)) | map(select(.analysisParameters.randomizeStrand == false))" "chrX:11,857,476" "" ${1}stats.json ${1}filtered.json
compare_jsons ${1}filtered.json ${1}filtered_no_range_exploration.json

extract_json "map(select(.analysisParameters.minBasePhredScoreQ2 == 28)) | map(select(.analysisParameters.minReadsPerStrandQ2 == 3)) | map(select(.analysisParameters.randomizeStrand == true))" "chrX:11,857,476" "" ${1}stats.json ${1}filtered.json
#echo '[{"blah": 0}]' >> filtered.json
extract_json "map(select(.analysisParameters.minBasePhredScoreQ2 == 30))" "chrX:11,857,476" "" ../../test_options/positive_strand/minBasePhredScoreQ2/test_Q2_score_27_criteria_30_no_detection/stats.json ${1}filtered_no_range_exploration.json
compare_jsons ${1}filtered.json ${1}filtered_no_range_exploration.json

touch run.out.check custom_check
