#!/usr/bin/env bash
set -e
set -o pipefail
source ../../../../bash_json_functions

extract_json "| map(select(.analysisParameters.randomizeStrand == true))" "chrX:11,857,475" ".disagreements" ${1}stats.json ${1}filtered.json
#Uncomment line below to check that error is generated if JSON objects differ
#echo '[{"blah": 0}]' >> filtered.json
compare_jsons ${1}filtered.json no_disagreements.json_preserve

extract_json "| map(select(.analysisParameters.randomizeStrand == false))" "chrX:11,857,475" ".disagreements" ${1}stats.json ${1}filtered.json
compare_jsons ${1}filtered.json deletion_disagreement.json_preserve

touch run.out.check custom_check
