#!/usr/bin/env bash
set -e
set -o pipefail
source ../../../../bash_json_functions

extract_json "| map(select(.analysisParameters.maxTopAlleleFreqQ2 == "0.9"))" "chrIV:14,941,896" ".disagreements" ${1}stats.json ${1}filtered.json
compare_jsons ${1}filtered.json no_disagreement.json_preserve
touch run.out.check custom_check
