// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uk/org/cinquin/mutinack/features/PosByPosNumbers.proto

package uk.org.cinquin.mutinack.features;

import java.util.Objects;

import org.eclipse.jdt.annotation.NonNull;

public final class PosByPosNumbersPB {
	private PosByPosNumbersPB() {}
	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}
	public interface ContigNumbersOrBuilder
	extends com.google.protobuf.MessageLiteOrBuilder {

		// required string contigName = 1;
		boolean hasContigName();
		String getContigName();

		// repeated int32 numbers = 2 [packed = true];
		java.util.List<java.lang.Integer> getNumbersList();
		int getNumbersCount();
		int getNumbers(int index);
	}
	public static final class ContigNumbers extends
	com.google.protobuf.GeneratedMessageLite
	implements ContigNumbersOrBuilder {
		// Use ContigNumbers.newBuilder() to construct.
		private ContigNumbers(Builder builder) {
			super(builder);
		}
		private ContigNumbers(boolean noInit) {}

		private static final ContigNumbers defaultInstance;
		public static ContigNumbers getDefaultInstance() {
			return defaultInstance;
		}

		@Override
		public ContigNumbers getDefaultInstanceForType() {
			return defaultInstance;
		}

		private int bitField0_;
		// required string contigName = 1;
		public static final int CONTIGNAME_FIELD_NUMBER = 1;
		private java.lang.Object contigName_;
		@Override
		public boolean hasContigName() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		@SuppressWarnings("null")
		@Override
		public @NonNull String getContigName() {
			java.lang.Object ref = contigName_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					contigName_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getContigNameBytes() {
			java.lang.Object ref = contigName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				contigName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// repeated int32 numbers = 2 [packed = true];
		public static final int NUMBERS_FIELD_NUMBER = 2;
		private int[] numbers_;
		private static java.util.List<java.lang.Integer> numbersArray2list(int[] numbers) {
			if(numbers == null) return null;
			java.util.ArrayList<java.lang.Integer> retList =
					new java.util.ArrayList<>(numbers.length);
			for(int f:numbers) retList.add(f);
			return retList;
		}
		private static java.util.List<java.lang.Integer> numbersArray2list(int[] numbers,int sizeLimit) {
			if(numbers == null) return null;
			int num2Copy = java.lang.Math.min(numbers.length,sizeLimit);
			java.util.ArrayList<java.lang.Integer> retList =
					new java.util.ArrayList<>(num2Copy);
			for(int i = 0;i<num2Copy;++i) retList.add(numbers[i]);
			return retList;
		}
		@Override
		public java.util.List<java.lang.Integer>
		getNumbersList() {
			if(numbers_ != null) return java.util.Collections.unmodifiableList(numbersArray2list(numbers_));
			else return java.util.Collections.emptyList();
		}
		@Override
		public int getNumbersCount() {
			return numbers_ != null ? numbers_.length : 0;
		}
		@Override
		public int getNumbers(int index) {
			// Note: don't check data_ if someone attempts
			// to grab on index that isn't available. Allow
			// JRE to simply throw NullPointException
			// or IndexOutOfBoundsException
			return numbers_[index];
		}
		// Note: that this exposes mutable data
		// for essentially an immutable type
		// To absolutely conform to the standard
		// we'd want to clone this array before
		// passing back but that would just incur
		// more inefficiency.
		public int[] getNumbersArray() {
			return numbers_;
		}
		private int numbersMemoizedSerializedSize = -1;

		private void initFields() {
			contigName_ = "";
			numbers_ = null;
		}
		private byte memoizedIsInitialized = -1;
		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasContigName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getContigNameBytes());
			}
			if (numbers_ != null && numbers_.length > 0) {
				output.writeRawVarint32(18);
				output.writeRawVarint32(numbersMemoizedSerializedSize);
				for (int i = 0; i < numbers_.length; ++i) {
					output.writeInt32NoTag(numbers_[i]);
				}
			}
		}

		private int memoizedSerializedSize = -1;
		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getContigNameBytes());
			}
			{
				int dataSize = 0;
				for (int i = 0; i < numbers_.length; ++i) {
					dataSize += com.google.protobuf.CodedOutputStream
							.computeInt32SizeNoTag(numbers_[i]);
				}
				size += dataSize;
				if (getNumbersCount() > 0) {
					size += 1;
					size += com.google.protobuf.CodedOutputStream
							.computeInt32SizeNoTag(dataSize);
				}
				numbersMemoizedSerializedSize = dataSize;
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		@Override
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		@Override
		public Builder toBuilder() { return newBuilder(this); }

		public static final class Builder extends
		com.google.protobuf.GeneratedMessageLite.Builder<
		uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers, Builder>
		implements uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbersOrBuilder {
			// Construct using uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}
			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				contigName_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				numbers_ = null;
				numUsedInNumbers_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers getDefaultInstanceForType() {
				return uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers.getDefaultInstance();
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers build() {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers buildPartial() {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers result = new uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.contigName_ = contigName_;
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					// Note: that it is not possible to make an array unmodifiable in Java
					// numbers_ = java.util.Collections.unmodifiableList(numbers_);
					bitField0_ = (bitField0_ & ~0x00000002);
				}
				result.numbers_ = numbers_ == null ? null :
					java.util.Arrays.copyOf(numbers_,numUsedInNumbers_);
				result.bitField0_ = to_bitField0_;
				return result;
			}

			@Override
			public Builder mergeFrom(uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers other) {
				if (other == uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers.getDefaultInstance()) return this;
				if (other.hasContigName()) {
					setContigName(other.getContigName());
				}
				if (other.numbers_ != null && other.numbers_.length > 0) {
					if (numbers_ == null) {
						numbers_ = other.numbers_;
						numUsedInNumbers_ = other.numbers_.length;
						bitField0_ = (bitField0_ & ~0x00000002);
					} else {
						ensureNumbersIsMutable();
						growNumbersArray(other.numbers_.length);
						for(int i = 0; i < other.numbers_.length; ++i) {
							numbers_[numUsedInNumbers_] = other.numbers_[i];
							++numUsedInNumbers_;
						}
					}

				}
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasContigName()) {

					return false;
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
						case 0:

							return this;
						default: {
							if (!parseUnknownField(input, extensionRegistry, tag)) {

								return this;
							}
							break;
						}
						case 10: {
							bitField0_ |= 0x00000001;
							contigName_ = input.readBytes();
							break;
						}
						case 16: {
							// This extra case for the numbers field is
							// used for extensibility in case the
							// field is changed in the future from
							// repeated to optional.
							addNumbers(input.readInt32());
							break;
						}
						case 18: {
							int length = input.readRawVarint32();
							int limit = input.pushLimit(length);
							while (input.getBytesUntilLimit() > 0) {
								addNumbers(input.readInt32());
							}
							input.popLimit(limit);
							break;
						}
					}
				}
			}

			private int bitField0_;

			// required string contigName = 1;
			private java.lang.Object contigName_ = "";
			@Override
			public boolean hasContigName() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			@Override
			public String getContigName() {
				java.lang.Object ref = contigName_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					contigName_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setContigName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				contigName_ = value;

				return this;
			}
			public Builder clearContigName() {
				bitField0_ = (bitField0_ & ~0x00000001);
				contigName_ = getDefaultInstance().getContigName();

				return this;
			}
			void setContigName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				contigName_ = value;

			}

			// repeated int32 numbers = 2 [packed = true];
			public int[] numbers_ = null;
			// transient just a hint that this isn't really a piece of data
			public transient int numUsedInNumbers_ = 0;
			private void ensureNumbersIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					if(numbers_ == null) {
						// This field will be grown by blocks of 20000 (that may require some
						// tweaking or an ability to be parameterized via metadata of some sort
						// Let's also start off with 20000 elements
						numbers_ = new int[20000];
					}
					bitField0_ |= 0x00000002;
				}
			}

			public void ensureNumbersIsMutable(int initialSize) {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					if(numbers_ == null && initialSize > 0) {
						numbers_ = new int[initialSize];
					}
					bitField0_ |= 0x00000002;
				}
			}
			private void growNumbersArray() {
				if(numbers_ == null) {
					ensureNumbersIsMutable();
				}
				else if(numUsedInNumbers_ >= numbers_.length) {
					// Grows our int[] by 20000 elements
					numbers_ = java.util.Arrays.copyOf(numbers_,numbers_.length + 20000);
				}
			}
			private void growNumbersArray(int byAdditional) {
				if(numbers_ == null) {
					ensureNumbersIsMutable();
				}
				if((numUsedInNumbers_ + byAdditional) >= numbers_.length) {
					numbers_ = java.util.Arrays.copyOf(numbers_,numUsedInNumbers_ + byAdditional);
				}
			}
			@Override
			public java.util.List<java.lang.Integer>
			getNumbersList() {
				return java.util.Collections.unmodifiableList(numbersArray2list(numbers_,numUsedInNumbers_));
			}
			@Override
			public int getNumbersCount() {
				return numUsedInNumbers_;
			}
			@Override
			public int getNumbers(int index) {
				if(index >= numUsedInNumbers_) throw new java.lang.IndexOutOfBoundsException();
				return numbers_[index];
			}
			// Note: It is not appropriate to add numbers to the returned
			// array because the internal counter numUsedInNumbers_ will
			// not be incremented properly!! Additionally, if used
			// as an Accessor only the getDataCount() number of
			// values are valid!
			public int[] getNumbersArray() {
				return numbers_;
			}
			public Builder setNumbers(
					int index, int value) {
				growNumbersArray();
				numbers_[numUsedInNumbers_] = value;

				return this;
			}
			public Builder addNumbers(int value) {
				ensureNumbersIsMutable();
				growNumbersArray();
				numbers_[numUsedInNumbers_] = value;
				++numUsedInNumbers_;

				return this;
			}
			public Builder addAllNumbers(
					java.lang.Iterable<? extends java.lang.Integer> values) {
				ensureNumbersIsMutable();
				int growBy = 0;
				for(@SuppressWarnings("unused") java.lang.Integer f:values) ++growBy;
				growNumbersArray(growBy);
				for(java.lang.Integer f:values) {
					numbers_[numUsedInNumbers_] = f;
					++numUsedInNumbers_;
				}

				return this;
			}
			public Builder clearNumbers() {
				numbers_ = null;
				numUsedInNumbers_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);

				return this;
			}

			// @@protoc_insertion_point(builder_scope:ContigNumbers)
		}

		static {
			defaultInstance = new ContigNumbers(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:ContigNumbers)
	}

	public interface GenomeNumbersOrBuilder
	extends com.google.protobuf.MessageLiteOrBuilder {

		// required string sampleName = 1;
		boolean hasSampleName();
		String getSampleName();

		// required string generatingProgramVersion = 2;
		boolean hasGeneratingProgramVersion();
		String getGeneratingProgramVersion();

		// required string generatingProgramArgs = 3;
		boolean hasGeneratingProgramArgs();
		String getGeneratingProgramArgs();

		// repeated .ContigNumbers contigNumbers = 4;
		java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers> 
		getContigNumbersList();
		uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers getContigNumbers(int index);
		int getContigNumbersCount();
	}
	public static final class GenomeNumbers extends
	com.google.protobuf.GeneratedMessageLite
	implements GenomeNumbersOrBuilder {
		// Use GenomeNumbers.newBuilder() to construct.
		private GenomeNumbers(Builder builder) {
			super(builder);
		}
		private GenomeNumbers(boolean noInit) {}

		private static final GenomeNumbers defaultInstance;
		public static GenomeNumbers getDefaultInstance() {
			return defaultInstance;
		}

		@Override
		public GenomeNumbers getDefaultInstanceForType() {
			return defaultInstance;
		}

		private int bitField0_;
		// required string sampleName = 1;
		public static final int SAMPLENAME_FIELD_NUMBER = 1;
		private java.lang.Object sampleName_;
		@Override
		public boolean hasSampleName() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		@Override
		public @NonNull String getSampleName() {
			java.lang.Object ref = sampleName_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					sampleName_ = s;
				}
				return Objects.requireNonNull(s);
			}
		}
		public void setSampleName(String sampleName) {
			sampleName_ = sampleName;
		}
		private com.google.protobuf.ByteString getSampleNameBytes() {
			java.lang.Object ref = sampleName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				sampleName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string generatingProgramVersion = 2;
		public static final int GENERATINGPROGRAMVERSION_FIELD_NUMBER = 2;
		private java.lang.Object generatingProgramVersion_;
		@Override
		public boolean hasGeneratingProgramVersion() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		@Override
		public String getGeneratingProgramVersion() {
			java.lang.Object ref = generatingProgramVersion_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					generatingProgramVersion_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getGeneratingProgramVersionBytes() {
			java.lang.Object ref = generatingProgramVersion_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				generatingProgramVersion_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string generatingProgramArgs = 3;
		public static final int GENERATINGPROGRAMARGS_FIELD_NUMBER = 3;
		private java.lang.Object generatingProgramArgs_;
		@Override
		public boolean hasGeneratingProgramArgs() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		@Override
		public String getGeneratingProgramArgs() {
			java.lang.Object ref = generatingProgramArgs_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					generatingProgramArgs_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getGeneratingProgramArgsBytes() {
			java.lang.Object ref = generatingProgramArgs_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				generatingProgramArgs_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// repeated .ContigNumbers contigNumbers = 4;
		public static final int CONTIGNUMBERS_FIELD_NUMBER = 4;
		private java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers> contigNumbers_;
		@Override
		public java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers> getContigNumbersList() {
			return contigNumbers_;
		}
		public java.util.List<? extends uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbersOrBuilder> 
		getContigNumbersOrBuilderList() {
			return contigNumbers_;
		}
		@Override
		public int getContigNumbersCount() {
			return contigNumbers_.size();
		}
		@Override
		public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers getContigNumbers(int index) {
			return contigNumbers_.get(index);
		}
		public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbersOrBuilder getContigNumbersOrBuilder(
				int index) {
			return contigNumbers_.get(index);
		}

		private void initFields() {
			sampleName_ = "";
			generatingProgramVersion_ = "";
			generatingProgramArgs_ = "";
			contigNumbers_ = java.util.Collections.emptyList();
		}
		private byte memoizedIsInitialized = -1;
		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasSampleName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasGeneratingProgramVersion()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasGeneratingProgramArgs()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getContigNumbersCount(); i++) {
				if (!getContigNumbers(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getSampleNameBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getGeneratingProgramVersionBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getGeneratingProgramArgsBytes());
			}
			for (int i = 0; i < contigNumbers_.size(); i++) {
				output.writeMessage(4, contigNumbers_.get(i));
			}
		}

		private int memoizedSerializedSize = -1;
		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getSampleNameBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(2, getGeneratingProgramVersionBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(3, getGeneratingProgramArgsBytes());
			}
			for (int i = 0; i < contigNumbers_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(4, contigNumbers_.get(i));
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		@Override
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		@Override
		public Builder toBuilder() { return newBuilder(this); }

		public static final class Builder extends
		com.google.protobuf.GeneratedMessageLite.Builder<
		uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers, Builder>
		implements uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbersOrBuilder {
			// Construct using uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}
			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				sampleName_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				generatingProgramVersion_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				generatingProgramArgs_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				contigNumbers_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers getDefaultInstanceForType() {
				return uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers.getDefaultInstance();
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers build() {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers buildPartial() {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers result = new uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.sampleName_ = sampleName_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.generatingProgramVersion_ = generatingProgramVersion_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.generatingProgramArgs_ = generatingProgramArgs_;
				if (((bitField0_ & 0x00000008) == 0x00000008)) {
					contigNumbers_ = java.util.Collections.unmodifiableList(contigNumbers_);
					bitField0_ = (bitField0_ & ~0x00000008);
				}
				result.contigNumbers_ = contigNumbers_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			@Override
			public Builder mergeFrom(uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers other) {
				if (other == uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers.getDefaultInstance()) return this;
				if (other.hasSampleName()) {
					setSampleName(other.getSampleName());
				}
				if (other.hasGeneratingProgramVersion()) {
					setGeneratingProgramVersion(other.getGeneratingProgramVersion());
				}
				if (other.hasGeneratingProgramArgs()) {
					setGeneratingProgramArgs(other.getGeneratingProgramArgs());
				}
				if (!other.contigNumbers_.isEmpty()) {
					if (contigNumbers_.isEmpty()) {
						contigNumbers_ = other.contigNumbers_;
						bitField0_ = (bitField0_ & ~0x00000008);
					} else {
						ensureContigNumbersIsMutable();
						contigNumbers_.addAll(other.contigNumbers_);
					}

				}
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasSampleName()) {

					return false;
				}
				if (!hasGeneratingProgramVersion()) {

					return false;
				}
				if (!hasGeneratingProgramArgs()) {

					return false;
				}
				for (int i = 0; i < getContigNumbersCount(); i++) {
					if (!getContigNumbers(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
						case 0:

							return this;
						default: {
							if (!parseUnknownField(input, extensionRegistry, tag)) {

								return this;
							}
							break;
						}
						case 10: {
							bitField0_ |= 0x00000001;
							sampleName_ = input.readBytes();
							break;
						}
						case 18: {
							bitField0_ |= 0x00000002;
							generatingProgramVersion_ = input.readBytes();
							break;
						}
						case 26: {
							bitField0_ |= 0x00000004;
							generatingProgramArgs_ = input.readBytes();
							break;
						}
						case 34: {
							uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers.Builder subBuilder = uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers.newBuilder();
							input.readMessage(subBuilder, extensionRegistry);
							addContigNumbers(subBuilder.buildPartial());
							break;
						}
					}
				}
			}

			private int bitField0_;

			// required string sampleName = 1;
			private java.lang.Object sampleName_ = "";
			@Override
			public boolean hasSampleName() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			@Override
			public String getSampleName() {
				java.lang.Object ref = sampleName_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					sampleName_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setSampleName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				sampleName_ = value;

				return this;
			}
			public Builder clearSampleName() {
				bitField0_ = (bitField0_ & ~0x00000001);
				sampleName_ = getDefaultInstance().getSampleName();

				return this;
			}
			void setSampleName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				sampleName_ = value;

			}

			// required string generatingProgramVersion = 2;
			private java.lang.Object generatingProgramVersion_ = "";
			@Override
			public boolean hasGeneratingProgramVersion() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			@Override
			public String getGeneratingProgramVersion() {
				java.lang.Object ref = generatingProgramVersion_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					generatingProgramVersion_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setGeneratingProgramVersion(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				generatingProgramVersion_ = value;

				return this;
			}
			public Builder clearGeneratingProgramVersion() {
				bitField0_ = (bitField0_ & ~0x00000002);
				generatingProgramVersion_ = getDefaultInstance().getGeneratingProgramVersion();

				return this;
			}
			void setGeneratingProgramVersion(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				generatingProgramVersion_ = value;

			}

			// required string generatingProgramArgs = 3;
			private java.lang.Object generatingProgramArgs_ = "";
			@Override
			public boolean hasGeneratingProgramArgs() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}
			@Override
			public String getGeneratingProgramArgs() {
				java.lang.Object ref = generatingProgramArgs_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					generatingProgramArgs_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setGeneratingProgramArgs(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				generatingProgramArgs_ = value;

				return this;
			}
			public Builder clearGeneratingProgramArgs() {
				bitField0_ = (bitField0_ & ~0x00000004);
				generatingProgramArgs_ = getDefaultInstance().getGeneratingProgramArgs();

				return this;
			}
			void setGeneratingProgramArgs(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000004;
				generatingProgramArgs_ = value;

			}

			// repeated .ContigNumbers contigNumbers = 4;
			private java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers> contigNumbers_ =
					java.util.Collections.emptyList();
			private void ensureContigNumbersIsMutable() {
				if (!((bitField0_ & 0x00000008) == 0x00000008)) {
					contigNumbers_ = new java.util.ArrayList<>(contigNumbers_);
					bitField0_ |= 0x00000008;
				}
			}

			@Override
			public java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers> getContigNumbersList() {
				return java.util.Collections.unmodifiableList(contigNumbers_);
			}
			@Override
			public int getContigNumbersCount() {
				return contigNumbers_.size();
			}
			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers getContigNumbers(int index) {
				return contigNumbers_.get(index);
			}
			public Builder setContigNumbers(
					int index, uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureContigNumbersIsMutable();
				contigNumbers_.set(index, value);

				return this;
			}
			public Builder setContigNumbers(
					int index, uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers.Builder builderForValue) {
				ensureContigNumbersIsMutable();
				contigNumbers_.set(index, builderForValue.build());

				return this;
			}
			public Builder addContigNumbers(uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureContigNumbersIsMutable();
				contigNumbers_.add(value);

				return this;
			}
			public Builder addContigNumbers(
					int index, uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureContigNumbersIsMutable();
				contigNumbers_.add(index, value);

				return this;
			}
			public Builder addContigNumbers(
					uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers.Builder builderForValue) {
				ensureContigNumbersIsMutable();
				contigNumbers_.add(builderForValue.build());

				return this;
			}
			public Builder addContigNumbers(
					int index, uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers.Builder builderForValue) {
				ensureContigNumbersIsMutable();
				contigNumbers_.add(index, builderForValue.build());

				return this;
			}
			public Builder addAllContigNumbers(
					java.lang.Iterable<? extends uk.org.cinquin.mutinack.features.PosByPosNumbersPB.ContigNumbers> values) {
				ensureContigNumbersIsMutable();
				addAll(values, contigNumbers_);

				return this;
			}
			public Builder clearContigNumbers() {
				contigNumbers_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000008);

				return this;
			}
			public Builder removeContigNumbers(int index) {
				ensureContigNumbersIsMutable();
				contigNumbers_.remove(index);

				return this;
			}

			// @@protoc_insertion_point(builder_scope:GenomeNumbers)
		}

		static {
			defaultInstance = new GenomeNumbers(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:GenomeNumbers)
	}

	public interface GeneratedFromOrBuilder
	extends com.google.protobuf.MessageLiteOrBuilder {

		// required string operation = 1;
		boolean hasOperation();
		String getOperation();

		// repeated .GenomeNumbers operands = 2;
		java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers> 
		getOperandsList();
		uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers getOperands(int index);
		int getOperandsCount();
	}
	public static final class GeneratedFrom extends
	com.google.protobuf.GeneratedMessageLite
	implements GeneratedFromOrBuilder {
		// Use GeneratedFrom.newBuilder() to construct.
		private GeneratedFrom(Builder builder) {
			super(builder);
		}
		private GeneratedFrom(boolean noInit) {}

		private static final GeneratedFrom defaultInstance;
		public static GeneratedFrom getDefaultInstance() {
			return defaultInstance;
		}

		@Override
		public GeneratedFrom getDefaultInstanceForType() {
			return defaultInstance;
		}

		private int bitField0_;
		// required string operation = 1;
		public static final int OPERATION_FIELD_NUMBER = 1;
		private java.lang.Object operation_;
		@Override
		public boolean hasOperation() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		@Override
		public String getOperation() {
			java.lang.Object ref = operation_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					operation_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getOperationBytes() {
			java.lang.Object ref = operation_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				operation_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// repeated .GenomeNumbers operands = 2;
		public static final int OPERANDS_FIELD_NUMBER = 2;
		private java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers> operands_;
		@Override
		public java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers> getOperandsList() {
			return operands_;
		}
		public java.util.List<? extends uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbersOrBuilder> 
		getOperandsOrBuilderList() {
			return operands_;
		}
		@Override
		public int getOperandsCount() {
			return operands_.size();
		}
		@Override
		public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers getOperands(int index) {
			return operands_.get(index);
		}
		public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbersOrBuilder getOperandsOrBuilder(
				int index) {
			return operands_.get(index);
		}

		private void initFields() {
			operation_ = "";
			operands_ = java.util.Collections.emptyList();
		}
		private byte memoizedIsInitialized = -1;
		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasOperation()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getOperandsCount(); i++) {
				if (!getOperands(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getOperationBytes());
			}
			for (int i = 0; i < operands_.size(); i++) {
				output.writeMessage(2, operands_.get(i));
			}
		}

		private int memoizedSerializedSize = -1;
		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getOperationBytes());
			}
			for (int i = 0; i < operands_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(2, operands_.get(i));
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		@Override
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		@Override
		public Builder toBuilder() { return newBuilder(this); }

		public static final class Builder extends
		com.google.protobuf.GeneratedMessageLite.Builder<
		uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom, Builder>
		implements uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFromOrBuilder {
			// Construct using uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}
			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				operation_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				operands_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom getDefaultInstanceForType() {
				return uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom.getDefaultInstance();
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom build() {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom buildPartial() {
				uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom result = new uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.operation_ = operation_;
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					operands_ = java.util.Collections.unmodifiableList(operands_);
					bitField0_ = (bitField0_ & ~0x00000002);
				}
				result.operands_ = operands_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			@Override
			public Builder mergeFrom(uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom other) {
				if (other == uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GeneratedFrom.getDefaultInstance()) return this;
				if (other.hasOperation()) {
					setOperation(other.getOperation());
				}
				if (!other.operands_.isEmpty()) {
					if (operands_.isEmpty()) {
						operands_ = other.operands_;
						bitField0_ = (bitField0_ & ~0x00000002);
					} else {
						ensureOperandsIsMutable();
						operands_.addAll(other.operands_);
					}

				}
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasOperation()) {

					return false;
				}
				for (int i = 0; i < getOperandsCount(); i++) {
					if (!getOperands(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
						case 0:

							return this;
						default: {
							if (!parseUnknownField(input, extensionRegistry, tag)) {

								return this;
							}
							break;
						}
						case 10: {
							bitField0_ |= 0x00000001;
							operation_ = input.readBytes();
							break;
						}
						case 18: {
							uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers.Builder subBuilder = uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers.newBuilder();
							input.readMessage(subBuilder, extensionRegistry);
							addOperands(subBuilder.buildPartial());
							break;
						}
					}
				}
			}

			private int bitField0_;

			// required string operation = 1;
			private java.lang.Object operation_ = "";
			@Override
			public boolean hasOperation() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			@Override
			public String getOperation() {
				java.lang.Object ref = operation_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					operation_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setOperation(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				operation_ = value;

				return this;
			}
			public Builder clearOperation() {
				bitField0_ = (bitField0_ & ~0x00000001);
				operation_ = getDefaultInstance().getOperation();

				return this;
			}
			void setOperation(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				operation_ = value;

			}

			// repeated .GenomeNumbers operands = 2;
			private java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers> operands_ =
					java.util.Collections.emptyList();
			private void ensureOperandsIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					operands_ = new java.util.ArrayList<>(operands_);
					bitField0_ |= 0x00000002;
				}
			}

			@Override
			public java.util.List<uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers> getOperandsList() {
				return java.util.Collections.unmodifiableList(operands_);
			}
			@Override
			public int getOperandsCount() {
				return operands_.size();
			}
			@Override
			public uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers getOperands(int index) {
				return operands_.get(index);
			}
			public Builder setOperands(
					int index, uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureOperandsIsMutable();
				operands_.set(index, value);

				return this;
			}
			public Builder setOperands(
					int index, uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers.Builder builderForValue) {
				ensureOperandsIsMutable();
				operands_.set(index, builderForValue.build());

				return this;
			}
			public Builder addOperands(uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureOperandsIsMutable();
				operands_.add(value);

				return this;
			}
			public Builder addOperands(
					int index, uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureOperandsIsMutable();
				operands_.add(index, value);

				return this;
			}
			public Builder addOperands(
					uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers.Builder builderForValue) {
				ensureOperandsIsMutable();
				operands_.add(builderForValue.build());

				return this;
			}
			public Builder addOperands(
					int index, uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers.Builder builderForValue) {
				ensureOperandsIsMutable();
				operands_.add(index, builderForValue.build());

				return this;
			}
			public Builder addAllOperands(
					java.lang.Iterable<? extends uk.org.cinquin.mutinack.features.PosByPosNumbersPB.GenomeNumbers> values) {
				ensureOperandsIsMutable();
				addAll(values, operands_);

				return this;
			}
			public Builder clearOperands() {
				operands_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000002);

				return this;
			}
			public Builder removeOperands(int index) {
				ensureOperandsIsMutable();
				operands_.remove(index);

				return this;
			}

			// @@protoc_insertion_point(builder_scope:GeneratedFrom)
		}

		static {
			defaultInstance = new GeneratedFrom(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:GeneratedFrom)
	}


	static {
	}

	// @@protoc_insertion_point(outer_class_scope)
}
